/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	char op;
	double a;
	double b;
};
typedef struct operandos operandos;

#define CALC_PROG 0x23456789
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULAR 1
extern  double * calcular_1(operandos *, CLIENT *);
extern  double * calcular_1_svc(operandos *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULAR 1
extern  double * calcular_1();
extern  double * calcular_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
